# Generated by Django 2.2.2 on 2019-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_auto_20190711_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
