# Generated by Django 2.2.2 on 2019-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_auto_20190716_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.RenameField(
            model_name='clipboard',
            old_name='name',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
