# Generated by Django 2.1.4 on 2019-07-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_auto_20190725_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
